### ISSUE TITLE
Auto import role and tag updates

### ISSUE THREAD

**Issue by gaieges** [ansible/galaxy-issues#189] opened 2016-09-09 20:43 UTC
I've updated a role a few times now, with new tags, only to go onto the ansible-galaxy page to see it not have the updates (even a day later).

This issue is to request the automatic importing of updates to roles and their tags from external sources.

**Comment by chouseknecht** [comment] 2016-09-30 05:49
You can do this by connecting the role to Travis. See https://galaxy.ansible.com/intro#travis for instructions.

**Comment by gaieges** [comment] 2016-09-30 15:42
So few things here:
- The documentation doesn't really even mention travis and the feature that if you have that set up, it will pull in updates on run.  Maybe I missed it, but perhaps that could be a little clearer?  (Looked all through that to start)
- It seems sort of orthogonal to have travis be required in order to have galaxy update roles that have changed on github, especially when tags are required to deploy to github, not necessarily a Travis run.  I get that maybe it saves some costs on your end (ie to have to poll all repos nightly or something), but its disjoint from the process of updating a repo whether you have travis or not, and getting it out to the world.
- I have that set up, and it doesnt seem to be doing that. (Open to doing something wrong)

**Comment by gaieges** [comment] 2016-11-05 22:25
Thoughts on this, @chouseknecht ?

Also bringing this back up as I thought I had it configured properly, yet my ansible galaxy role still doesn't seem to get updated (tags particularly) with a properly setup travis token, configuration, and link to the galaxy/github.

**Comment by tersmitten** [comment] 2016-11-06 07:31
I have the same issue for my roles under /tersmitten and /Oefenweb. Auto updates used to work in the past.

**Comment by tersmitten** [comment] 2016-11-10 11:59
@chouseknecht Any updates on this?

**Comment by geerlingguy** [comment] 2016-11-14 15:43
+1 on this—I haven't been getting any of my roles updated in the past month or so...

**Comment by chouseknecht** [comment] 2016-11-14 18:07
Apologies for not seeing this until today. There's definitely an issue. POST requests to /api/v1/notifications are resulting in a 400 response. Working now on tracking down the issue.

**Comment by tersmitten** [comment] 2016-11-14 19:36
No worries @chouseknecht, thanks for looking into it now

**Comment by chouseknecht** [comment] 2016-11-14 21:09
So it seems that using the Travis token to verify the inbound request to Galaxy is now completely deprecated. https://github.com/travis-ci/travis-ci/issues/6435

The requests are being denied on our end because the HTTP_AUTHORIZATION header is no longer being sent. The documentation says it should still be there, but it's not.

Working on implementing the new verification method...

**Comment by tersmitten** [comment] 2016-11-14 21:14
This is probably what you're looking for https://twitter.com/travisci/status/793820549101199360

**Comment by geerlingguy** [comment] 2016-11-14 21:58
@chouseknecht - Can we reopen this ticket, maybe, or create a new one, just so I (and others who run into the issue) have a reference to check up on (instead of pestering you via other avenues ;).

**Comment by chouseknecht** [comment] 2016-11-15 22:10
I pushed a fix to the [Galaxy QA site](https://galaxy-qa.ansible.com).
- It implements [new method of verifying webhook requests](https://docs.travis-ci.com/user/notifications#Verifying-Webhook-requests)
- Travis tokens are no longer required, so removed the entry form from My Roles page
- Removed mention of Travis tokens on the About page.
- If the github_user received in TRAVIS_REPO_SLUG header matches a Galaxy user, then the import request is created for that user. If no match, then we create the import task and assign it to one of our GitHub task accounts. 
- Added a "Last 10 Imports" section on the role detail page to provide some way of verifying a role was imported, in the event that the import task was assigned to a task account . The import details can be seen in the API, may work on surfacing them on the role details page.

If anyone has time to try this out and verify that things work, I would appreciate it. I have tested with a couple test roles, and it seems to work. To test it, update your .travis.yml file by setting _notifications: webhooks: url:_ to _https://galaxy-qa.ansible.com/api/v1/notifications/_

Thanks!

**Comment by chouseknecht** [comment] 2016-11-15 22:10
@gregdek ^

**Comment by gregdek** [comment] 2016-11-16 16:59
I'll talk to the Ansible QA team to see if they can get some cycles on this.

**Comment by mattclay** [comment] 2016-11-16 22:16
@chouseknecht I just created a new role, signed up for Galaxy and configured Travis on both galaxy and galaxy-qa. I've confirmed that the automatic import on build from Travis works for galaxy-qa and is not working for galaxy.

**Comment by chouseknecht** [comment] 2016-11-17 03:44
Thanks @mattclay 

Change pushed to Galaxy. Let me know, if we're good to close this issue.

**Comment by mattclay** [comment] 2016-11-17 05:26
@chouseknecht Tested and working on `galaxy.ansible.com` now. Thanks!

**Closed as completed by mattclay** 2016-11-17 05:26 UTC
