### ISSUE TITLE
Can't delete roles using Web UI for repos that don't exist/have been renamed

### ISSUE THREAD

**Issue by emonty** [ansible/galaxy-issues#187] opened 2016-09-06 17:22 UTC
https://galaxy.ansible.com/openstack-infra/puppet/ is a role in galaxy that was imported in February from the repo openstack-infra/ansible-puppet. Since then, that repo has been renamed to openstack-infra/ansible-role-puppet to be more inline with the ansible-role-$foo naming scheme. However, I can't import openstack-infra/ansible-role-puppet to openstack-infra.puppet because there is already something there - and I can't delete it because the role management page only shows repos that exists since it's driven by looking at the list of repos you have access to.

Short term - could someone delete that role for me? Long term - can we make a mechanism to allow deleting roles that no longer have valid github repos?

**Comment by c-mart** [comment] 2016-09-12 23:27
I also cannot delete [this role](https://galaxy.ansible.com/CyVerse-Ansible/hello-test/) from Galaxy that I created for testing, and then deleted the source repository. 

![screenshot_2016-09-12_16-26-45](https://cloud.githubusercontent.com/assets/13605043/18456446/cd677e72-7905-11e6-955c-cf2627b211af.png)

I click the red DELETE button and nothing happens.

**Comment by chouseknecht** [comment] 2016-09-30 06:13
We could probably automate this with a background task that deletes Galaxy roles that no longer exist GitHub.
- openstack-infra.puppet role is deleted. 
- cyverse-ansble.hello-test is deleted

**Comment by chouseknecht** [comment] 2016-10-16 09:22
- Added a background task that removes roles where the GitHub repository is no longer accessible and updates roles where the GitHub repository has been renamed. 
- The refresh process in the UI (on _My Roles_ page) also removes user roles where the repository is no longer accessible and updates roles when the repository name has changed.
- When deleting a role through the UI, the process now traps the error that occurs when the repository was previously deleted. When this happens the user is notified that they need to click the _Refresh_ button. And as mentioned above, the refresh process will remove any roles where the GitHub repo cannot be accessed and update roles with the correct repository name when the repository name has changed.

Marking as closed. However, if the error persists, please re-open.

**Closed as completed by chouseknecht** 2016-10-16 09:22 UTC
Labels: enhancement

**Comment by chouseknecht** [comment] 2016-10-16 09:34
@emonty - btw, the [puppet role](https://galaxy.ansible.com/openstack-infra/puppet/) is no longer. It has been removed from the database as well.

@c-mart the hello-test role has been completely removed.

**Comment by alpegon** [comment] 2016-11-07 09:45
Hi, several days ago I've created a role called https://galaxy.ansible.com/grycap/rol-nfs/ based on the github repo https://github.com/grycap/ansible-rol-nfs.
As you realize the name is incorrect (rol instead of role), so I've modified the github project and changed the name to https://github.com/grycap/ansible-role-nfs.
Now I have two projects in the main page of the organization: https://galaxy.ansible.com/grycap/:
- https://galaxy.ansible.com/grycap/nfs/: correct
- https://galaxy.ansible.com/grycap/rol-nfs/: incorrect  

Both of them point to the same github repo (the modified one https://github.com/grycap/ansible-role-nfs).
The problem is that old github project (rol-nfs) doesn't apper under 'my roles ' project list and I cannot delete or modify it.

I've also tried to update the project list but when I click on the refresh button in my roles page, the refresh keeps running forever.

Could someone check this behaviour please? 
Thank you very much

**Comment by alpegon** [comment] 2016-11-09 10:07
Ok, I've deleted the role grycap/ansible-role-nfs from ansible galaxy and both of the organization roles disappeared.
Problem solved.

**Comment by skuark** [comment] 2016-11-14 23:27
Hi. I am experiencing a similar issue after renaming some ansible role repositories on GitHub. I can't re-import neither delete old ones. The problematic repos are in the profile https://galaxy.ansible.com/dlcoder/
