### ISSUE TITLE
'My Roles' not displaying all roles

### ISSUE THREAD

**Issue by kbrebanov** [ansible/galaxy-issues#107] opened 2016-01-28 17:09 UTC
Look like the 'My Roles' page only lists the first 100 repositories from GitHub.

**Comment by chouseknecht** [comment] 2016-02-04 06:15
Started tracking this down. The issue is in pagination of the RepositoryList view. It's not a front-end problem.

**Comment by chouseknecht** [comment] 2016-02-08 04:41
Fixed. There was actually a setting for max page size. Bumped it from 100 to 1000. This is fixed in production.

**Closed as completed** 2016-03-01 14:30 UTC
Labels: bug, shipit
