### ISSUE TITLE
Cannot name role 'ansible'

### ISSUE THREAD

**Issue by tersmitten** [ansible/galaxy-issues#69] opened 2015-08-31 15:41 UTC
I created a role that installs Ansible. It is named `ansible`. It looks like `ansible` is a reserved word or something because it's not displayed in the UI:
- https://galaxy.ansible.com/list#/roles/4397
- https://galaxy.ansible.com/accounts/profile/#/

**Comment by aussielunix** [comment] 2015-09-15 00:26
Duplicate of https://github.com/ansible/galaxy-issues/issues/53

**Comment by geerlingguy** [comment] 2015-09-15 19:49
See also https://github.com/ansible/ansible/issues/11556

**Comment by gregdek** [comment] 2015-10-22 18:56
OK, closing this as duplicate of #53. We'll get it sorted out. :)

**Closed as completed by gregdek** 2015-10-22 18:56 UTC
