### ISSUE TITLE
Role listed multiple (2) times

### ISSUE THREAD

**Issue by groggemans** [ansible/galaxy-issues#109] opened 2016-01-29 22:54 UTC
Can't seem to recreate the issue but I was working on my roles and one of them was suddenly listed twice under my roles. Disabling/enabling didn't solve the issue, renewing the list did.

**Comment by MiLk** [comment] 2016-02-02 01:36
I had a same issue soon after the release of the new version.
After doing a few refresh and imports, it seems to be ok.
I had to disable/enable a few roles.

**Comment by chouseknecht** [comment] 2016-02-08 04:09
Fixed pushed to galaxy-qa.ansible.com. Duplicate of issue 117.

**Closed as completed** 2016-03-01 14:30 UTC
Labels: bug, ready for testing
