### ISSUE TITLE
Ad-blocker blocks vital content

### ISSUE THREAD

**Issue by groggemans** [ansible/galaxy-issues#106] opened 2016-01-28 10:58 UTC
With an active ad-blocker, a lot of the functionality is not working in galaxy 2.

It would be nice if there was a message that tells people to disable there ad-blockers on galaxy. (not needed anyway)

_(I'm using uBlock Origin)_

**Comment by chouseknecht** [comment] 2016-01-28 11:04
This is a duplicate of https://github.com/ansible/galaxy-issues/issues/101

**Comment by groggemans** [comment] 2016-01-28 11:11
Oops, missed that one, sorry!

**Closed as completed** 2016-02-07 20:15 UTC
