### ISSUE TITLE
Removed roles still can be found in galaxy-explore

### ISSUE THREAD

**Issue by zxcvbnius** [ansible/galaxy-issues#171] opened 2016-07-22 04:26 UTC
Hello everyone, 

I am newbie here. I uploaded my first ansible role [zxcvbnius.practice](https://galaxy.ansible.com/zxcvbnius/practice/) this morning.
Before uploading successfully  I deleted the role from my management page but the role still can be found in [explore](https://galaxy.ansible.com/zxcvbnius/practice/). 
I am not sure if there’s anything I did wrong. 

Thanks!

**Comment by s-hertel** [comment] 2016-07-26 15:40
Hi! Congrats on your first upload.

Requesting some more information:
How did you try to delete the role from your management page? The repo your galaxy.ansible role was derived from (https://github.com/zxcvbnius/ansible-practice) seems to no longer be there. Did you delete that? If you click on the MyRoles tab on galaxy.ansible.com do you see zxcvbnius.practice listed? Or can you only find it in Explore?

If you have more questions, please don't hesitate. If you haven't been using the GalaxyCLI someone with access to the private galaxy repo will need to look at this (though if you're looking for a workaround you could try using the command line). 

Using the command line you should be able to remove your role from galaxy.ansible.com by typing:
ansible-galaxy login
ansible-galaxy delete your_github_username the_github_repo

**Comment by zxcvbnius** [comment] 2016-08-11 05:54
Hi @s-hertel,
Thanks for your reply and so sorry for late response. Yes, I deleted my github repo without removing the role in MyRoles. This might be the problem.  

I still can find zxcvbnius.practice in MyRoles and Ansible Galaxy Explore
[myroles-screenshot](https://www.dropbox.com/s/k6qw1xnlfwtdjhc/myRoles.png?dl=0) and [explore-screenshot](https://www.dropbox.com/s/gmso3isdgb196dh/explore.png?dl=0)  

Using the command 'ansible-galaxy list' I cannot find the role in the list.
[command-screenshot](https://www.dropbox.com/s/dyo189k7tpnk8v3/command-galaxy-list.png?dl=0)  

Many thanks!

**Comment by chouseknecht** [comment] 2016-10-07 20:03
duplicate of #187

**Closed as completed by chouseknecht** 2016-10-07 20:03 UTC
Labels: needs_info
